### ISSUE TITLE
Hide pickup point id

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#110]
Current implementation show's pickup point id in order view. That has no value to anyone, so it needs to be hidden.

**Comment by k1sul1** [comment]
It's read straight from the database. 

`SELECT * FROM wp_postmeta WHERE meta_key = '_pakettikauppa_pickup_point'`

Is there any point in saving it to the database in the first place? If not, removing it that way seems easiest.

**Comment by joosev** [comment]
Only thing needed in the database is the pickup point ID

**Comment by joosev** [comment]
Then we can use some new API call to fetch pickup point information related to that ID if we need to display pickup point information.

**Comment by k1sul1** [comment]
Since there are possibly hundreds of installations which have potentially thousands of orders which have saved the rather lengthy string to`_pakettikauppa_pickup_point`, it would be best to deprecate the field `_pakettikauppa_pickup_point` entirely and create a new field `_pakettikauppa_pickup_point_id` that's used for that purpose.

I can't say that I'm a fan of making an API call to a 3rd party (Pakettikauppa) server to display information for a spesific pickup point. If Pakettikauppa servers are down, order management screens on the end user stores are down too, or at least slowed down significantly.

**Comment by joosev** [comment]
Pickup point info can be saved too. Merchants don't need to see the ID of the pickup point.
