### ISSUE TITLE
incorrect pickup location is chosen

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#12]
Correct shipping method is automaticly chosen, but user defined pikcup point is not.

**Comment by l3ku** [comment]
I can't seem to reproduce the problem, the pickup point that the user chose when making an order is automatically selected in the order edit screen in wp-admin. Could you provide which service and pickup point you chose that caused this behaviour, screenshot etc.?

**Comment by serter** [comment]
Maybe this explains it, see the attached images. Same order, nothing has changed between images except config option woocommerce_WC_Pakettikauppa_Shipping_Method_pickup_points_search_limit

The list is different in frontend (while making an order) and backend (while editing it).

![piste_5](https://user-images.githubusercontent.com/1519376/32938564-46729c48-cb85-11e7-9d54-a766c4e88a56.png)
![piste_10](https://user-images.githubusercontent.com/1519376/32938566-496d1662-cb85-11e7-9a4a-aaf7c6ba71c4.png)

The shorter 5 pickup points list doesnt include the selected pickup point at all! So the first/default/selected item is chosen when creating the label.

**Comment by l3ku** [comment]
The problem is in the function that prints the meta box output. The pickup points are searched only by using the shipping post code, without any service specified: https://github.com/Seravo/woo-pakettikauppa/blob/bcb0d0f88dcaaf48ff0e34f998ef831b1b538b63/includes/class-wc-pakettikauppa-admin.php#L279

For a reference, see how the function is called in the Frontend side:
https://github.com/Seravo/woo-pakettikauppa/blob/bcb0d0f88dcaaf48ff0e34f998ef831b1b538b63/includes/class-wc-pakettikauppa.php#L113

However, when changing the shipping service from the meta box in WP Admin, the pickup points are not refreshed automatically (like in the frontend WooCommerce order form). This should be manually reimplemented in such a way, that a change of shipping service triggers a new pickup point search (via AJAX).

**Comment by l3ku** [comment]
As with ea3b585 and 9941630, the pickup point field filter has been removed from the WooCommerce pickup point screen and the get_pickup_points function is called similarily in both cases. Now the retrieved pickup points are the same, but they are not filtered according to pickup point. The screenshots below:

**WooCommerce Checkout**
![screen shot 2017-11-21 at 18 05 02](https://user-images.githubusercontent.com/24781811/33083135-39f59064-cee7-11e7-8ca9-8ae4ce7671a9.png)

**Order View in WP Admin**

![screen shot 2017-11-21 at 18 24 04](https://user-images.githubusercontent.com/24781811/33083891-36fb29c6-cee9-11e7-95a1-0759a51f685c.png)

We should probably provide functionality described in the comment above: the pickup points should also be filtered according to service provider in WP Admin, but this feature still requires some planning. Thus, this issue is still kept open for now.

**Comment by joosev** [comment]
Bug is fixed with the issue #18

**Comment by tatusah** [comment]
![image](https://user-images.githubusercontent.com/17417945/34035186-e80e4c72-e189-11e7-9edc-2736a5718e7e.png)

Should this already be fixed? The pickup location dropdown still seems to show pickup locations for all the shipping providers even when the provider is already selected. This leads to possible issues where customer can make conflicting selections where e.g. selected provider is Posti but the pickup location is for Matkahuolto.

**Comment by joosev** [comment]
This is fixed and there is a pull request for this.

![nayttokuva 2017-12-15 kello 12 12 08](https://user-images.githubusercontent.com/14106091/34037385-48bb8326-e191-11e7-8431-ab58cdc411a7.png)

**Comment by joosev** [comment]
That fix is not optimal, but was easy enough to implement to fix the problem. Optimal solution should use ajax and only fetch required pickup points from a correct provider.

**Comment by joosev** [comment]
But for now, this not so optimal fix is better than current solution that allows users to choose pickup points that do not exists.

**Comment by l3ku** [comment]
The fix mentioned above was added in 55074aed1541237dc0deaf3ee7c42763a96399a3. However, pickup points should also be filtered actively via AJAX based on the chosen service provider in the wp-admin order view metabox – a feature which still remains unimplemented, at least for now. Thus, leaving the issue open.
