### ISSUE TITLE
Version requirement for composer/installers prevents installing via composer in a Bedrock based project

### ISSUE THREAD

**Issue by mattijv** [Pakettikauppa/woo-pakettikauppa#121]
This plugin has a strict requirement for a specific version of composer/installers (locked at v1.0.12), which conflicts with the version required by the [Bedrock Wordpress stack](https://github.com/roots/bedrock) (^1.7).

Is there a particular reason this plugin won't work with a newer version of the composer/installers package, and/or is this plugin incompatible with the Bedrock stack for some other reason?

**Comment by mattijv** [comment]
To clarify: installing with wp-cli still works, but for version control reasons installing via composer would be preferable.

**Comment by ottok** [comment]
I don't recall any particular version. I think we locked it to that version simply to keep things stable, since new versions of the composer installer often changes behaviour and breaks things. If you can confirm that the new ^1.7 forks for you, then we can proceed to update it in the project template.

**Comment by mattijv** [comment]
So I tested this out by creating a fork of the plugin and changing the composer.json to match the requirements in the Bedrock project, i.e. I changed the composer/installers requirement to "^1.7".

After installing the forked plugin with composer and activating it with wp-cli I got the following trace after accessing the admin view:

![Screenshot from 2020-01-17 13-36-02](https://user-images.githubusercontent.com/1974547/72609955-def37f00-392e-11ea-9b3c-080a090a2fa2.png)

I did not try to debug it more.

Curiosly, however, if I first install and activate the plugin with

`wp plugin install --activate woo-pakettikauppa`

and immediately delete it with

`wp plugin delete woo-pakettikauppa` and then try to install it with composer, the composer installation works just fine (I did not test all functionality, but nothing immediately obvious was broken).

Unfortunately I'm not experienced in WP development enough (read: not at all) to say if the problem is with using the newer version of composer/installers, or something else.

## Testing environment
Basic [Bedrock installation](https://roots.io/bedrock/docs/installing-bedrock/) with WP 5.3.2 and woocommerce and woo-pakettikauppa plugins, running on a virtual machine using the default [Trellis](https://roots.io/trellis/docs/installing-trellis/) configuration.

**Comment by ottok** [comment]
This is not a PHP error not a warning, just a notice. The undefined index could be due to various reasons, hard to guess anything without access to the installation. Let us know if you figure it out!

I have at least not personally reviewed the changelog of Composer 1.7, so I don't have any guesses either on what change this might be related to (or if this really is even related, since it is just a notice).

**Comment by k1sul1** [comment]
What's the point of having any of these in the require section of composer.json?

```
    "php": ">=7.0",
    "composer/installers": "v1.0.12",
    "ext-simplexml": "*"
```

php and ext-simplexml are both unnecessary requirements, if some unfortunate soul is running composer on php5, they can't install this, even if the actual code is running on 7. 

Is composer/installers really required? I don't use it any of my plugins and I can install them just fine with composer, probably because composer/installers is listed next to the actual dependencies.

I propose we just delete those requirements as unnecessary. :-1: / :+1: ?

**Comment by joosev** [comment]
I suppose ext-simplexml is not needed here, because Pakettikauppa api-library already has that as requirement.

**Comment by joosev** [comment]
if someone is using php5 and trying to run composer just to install, they can use --ignore-platform-reqs option

**Comment by joosev** [comment]
Implementing this does not break anything that we know?

**Comment by k1sul1** [comment]
IMO Composer is ridiculously unfriendly to debug whenever there's a problem. You have to know the exact things to google to get to the next step of whatever you were trying to do, since the error output from Composer is far from helpful. 

AFAIK & IIRC it doesn't mention the existence of that flag when the requirements fail. Which is why I'd remove all of them. WP won't allow the plugin activation if it can't run so...

Removing all 3 should be fine, it'll only affect the Composer installation anyway. Which is broken at the moment.
