### ISSUE TITLE
Pickup point chooser for custom shipping options

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#125]
As a merchant I want to create a custom shipment for the customer using other pickup point that the customer have chosen.
----
When creating a custom shipment, if the shipping method supports pickup points, then display pickup point selector similar in the checkout. Don't overwrite the original chosen pickup point.

**Comment by k1sul1** [comment]
Requires further refactoring (rewriting JS etc) to be done properly.

> display pickup point selector similar in the checkout

with a custom address selector or just options from the shipping address in the order?

**Comment by joosev** [comment]
Yes, this is not that easy as it might look at first.

Custom address selector: yes

**Comment by k1sul1** [comment]
This is going to need a lot more than just JS rewrites... I've spent over 8 hours on this today and accomplished nothing meaningful. Calling the code around this feature spaghetti would be putting it nicely. At this point I think it would be easier to rewrite the entire thing. I change a tiny thing in order to to try and make things work and 2 other things break.

It searches the pickup points alright with the initial value but that's just about the only thing that works correctly at this point. 

![image](https://user-images.githubusercontent.com/2719615/75614306-211ffb00-5b40-11ea-813f-89791c0b9906.png)
![image](https://user-images.githubusercontent.com/2719615/75614313-2ed58080-5b40-11ea-9441-14214a1c545b.png)

The little that has been done can be seen on [feature/pickuppointchoosercustomoptions](https://github.com/Seravo/woo-pakettikauppa/tree/feature/pickuppointchoosercustomoptions)
