### ISSUE TITLE
Make admin side features ajax

### ISSUE THREAD

**Issue by joosev** [Pakettikauppa/woo-pakettikauppa#37]
- Create shipment
- Update status
- delete shipping label

**Comment by l3ku** [comment]
The meta box features are now implemented with AJAX. However, the order notes are not immediately displayed after doing the AJAX action because they are implemented with `WC_Order::add_order_note` in the AJAX handler, which requires refreshing the page to display them. The order notes can be used, but the error/success messages should be displayed dynamically with JavaScript so that the user knows what is going on.

**Comment by joosev** [comment]
Yes, this is a problem. Woo does not - at the moment - offer ajax refresh feature on order notes, so another solution has to be implemented. This is a issue I am looking into.

**Comment by joosev** [comment]
Implemented in 2.0.16 basic error handling: if error happens, reload the page. otherwise evyrything is done in AJAX
